[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deepkoopformer"
version = "0.1.0"
description = "Koopman-augmented transformer models for scientific time series forecasting"
authors = [
    { name="Ali Forootani", email="aliforootani@ieee.org" }
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

dependencies = [
    "numpy==1.24.4",
    "pandas==1.5.3",
    "matplotlib==3.7.1",
    "scikit-learn==1.2.2",
    "scipy==1.10.1",
    "torch==2.0.1",
    "seaborn>=0.13.2",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "isort"
]
docs = [
    "sphinx",
    "numpydoc"
]


[tool.setuptools]
packages = ["deepkoopformer"]

[tool.setuptools.package-data]
# Only include data for your main package, if needed
"deepkoopformer" = []

# Remove exclude-package-data for examples as it's irrelevant now

